config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :inquiries, only:[:index, :new, :create]
  root 'inquiries#index'
 
 resources :answers, only:[:new, :create]
  
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :inquiry
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    
    has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    

    def new
        @answer = Answer.new
    end

    
    def create
        @answer = Answer.new(answer_params)
        if @answer.save
            SampleMailer.send_when_create_answer(@answer).deliver
        else
            render 'new'
        end
    end
    
    
    
    private
    
    def answer_params
        params.require(:answer).permit(:inqiry_id, :content)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
    
    
    def index
        @inquries = Inquiry.all.order(created_at: :desc)
        @answers= Answer.all.order(created_at: :desc)
    end
    
    
    def new
        @inquiry = Inquiry.new
    end
    
    
    def create
        @inquiry = Inquiry.new(inquiry_params)
        #respond_to do |format|
        if @inquiry.save
            SampleMailer.send_when_create(@inquiry).deliver   #確認メールを送信（メッセージを送信したよ)
            redirect_to inquiries_path
            #format.html { redirect_to inquiries_path, notice: 'Message was successfully sent.' }
            #format.json { render :index, status: :created, location: @inquiry }#メールが送信された現状:statusと:locaationは表示するurl
        else
            render 'new'
            #format.html { render :new } #newアクションに飛ばしている。
            #format.json { render json: @inquiry.errors, status: :unprocessable_entity }#おそらくエラーメッセージを出すためのコード
        end
        
        
        
    end
    
    private
    
    def inquiry_params
        params.require(:inquiry).permit(:name, :email, :content)
    end
    
    
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/answers/new.html.erb
<h2>test お問い合わせ</h2>
<%= form_for @answer do |f| %>
<p><%= f.text_area :content %></p>
<p><%= f.submit "送信" %></p>
<% end %>

<%= link_to '質問一覧', inquiries_path %>

app/views/inquiries/index.html.erb
<% i=0 %>
<% @inquries.each do |inquiry| %>
    <% @answers.each do |answer| %>
        <% if inquiry.id == answer.inquiry_id %>
            <p>質問内容</p>
            <%= i+=1 %><p><%= inquiry.content %></p>
            <p>回答</p>
            <p><%= answer.content %></p>
        <% end %>
    <% end %>
<% end %>

<hr>
<%= link_to 'お問い合わせ', new_inquiry_path %>
<%= link_to '回答', new_answer_path %>
    
        
        

app/views/inquiries/new.html.erb
<h2>test お問い合わせ</h2>
<%= form_for @inquiry do |f| %>
<p><%= f.text_field :name %></p>
<p><%= f.text_field :email %></p>
<p><%= f.text_area :content %></p>
<p><%= f.submit "送信" %></p>
<% end %>

<%= link_to '質問一覧', inquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>